# Generated by Django 5.2 on 2025-08-07 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('max_capacity', models.PositiveIntegerField(default=10, help_text='Maximum bookings for this time slot')),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_time_slots', to='restaurant.restaurant')),
            ],
            options={
                'ordering': ['date', 'time'],
                'unique_together': {('restaurant', 'date', 'time')},
            },
        ),
    ]
