# Generated by Django 5.2 on 2025-08-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('waiter', 'Waiter'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
