# Generated by Django 5.2 on 2025-08-07 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerusage',
            options={'ordering': ['-used_at']},
        ),
        migrations.RemoveField(
            model_name='offer',
            name='promo_code',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='total_usage_limit',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='usage_limit_per_user',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='valid_time_end',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='valid_time_start',
        ),
        migrations.AddField(
            model_name='offer',
            name='current_uses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of times this offer can be used', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_uses_per_user',
            field=models.PositiveIntegerField(default=1, help_text='Maximum uses per user', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='offer',
            name='valid_from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='valid_until_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerusage',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerusage',
            name='order_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For fixed amount discounts', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For percentage discounts (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='maximum_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount for percentage offers', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='minimum_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount'), ('bogo', 'Buy One Get One'), ('combo', 'Combo Deal'), ('special', 'Special Offer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='valid_days',
            field=models.JSONField(blank=True, default=list, help_text="Days when offer is valid (e.g., ['monday', 'tuesday'])"),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['restaurant', 'is_active'], name='offers_offe_restaur_c03cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['valid_from', 'valid_until'], name='offers_offe_valid_f_43f1a4_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['offer_type'], name='offers_offe_offer_t_305478_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_featured'], name='offers_offe_is_feat_d2da2c_idx'),
        ),
    ]
