# Generated by Django 5.2 on 2025-08-08 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offeractivation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offerusage',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='offerusage',
            index=models.Index(fields=['offer', 'user'], name='offers_offe_offer_i_235cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='offerusage',
            index=models.Index(fields=['used_at'], name='offers_offe_used_at_5b394b_idx'),
        ),
    ]
