# Generated by Django 5.2 on 2025-08-08 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offerusage_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offerusage',
            name='status',
            field=models.CharField(choices=[('used', 'Actually Used'), ('expired', 'Expired Without Use')], default='used', max_length=20),
        ),
        migrations.AddIndex(
            model_name='offerusage',
            index=models.Index(fields=['status'], name='offers_offe_status_082e5e_idx'),
        ),
    ]
