# Generated by Django 5.2 on 2025-08-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_offerusage_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerusage',
            name='used_at',
            field=models.DateTimeField(),
        ),
    ]
