# Generated by Django 5.2 on 2025-08-08 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_offerusage_used_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offerusage',
            name='activation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_record', to='offers.offeractivation'),
        ),
        migrations.AddIndex(
            model_name='offerusage',
            index=models.Index(fields=['activation'], name='offers_offe_activat_7404ec_idx'),
        ),
    ]
