# Generated by Django 5.2 on 2025-08-08 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_offerusage_activation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='offerusage',
            constraint=models.UniqueConstraint(condition=models.Q(('activation__isnull', False)), fields=('activation',), name='unique_usage_per_activation'),
        ),
    ]
