# Generated by Django 5.2 on 2025-08-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_add_unique_usage_per_activation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='valid_from_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='valid_until_time',
        ),
    ]
